# Japanese (normalized by norm.norm) -> English.  "{GAP}" marks where the original
# text left blank space for a graphic symbol.
G = {
 '%%C42.3(R9の中心)': '%%C42.3 (CENTER OF R9)',
 '%%C<>(R8の中心)': '%%C<> (CENTER OF R8)',
 '%%U断面図': '%%USECTION VIEW',
 '%%c<>(取付穴径)': '%%c<> (MOUNTING HOLE DIA.)',
 '(%%C<>以上)': '(%%C<> MIN.)',
 '(*印間)': '(BETWEEN *)',
 '(両端)': '(BOTH ENDS)',
 '(取付穴径)': '(MOUNTING HOLE DIA.)',
 '(手仕上げ可)': '(HAND FINISHING ACCEPTABLE)',
 '(有色クロメート)': '(YELLOW CHROMATE)',
 '(株)小松製作所': 'KOMATSU LTD.',
 '0.5mm以下': '0.5 mm MAX.',
 '1)軸方向荷重(P方向)': '1) AXIAL LOAD (P DIRECTION)',
 '1)雨水、日射あり。': '1) EXPOSED TO RAIN AND SUNLIGHT.',
 '1)雨水、日射有り。': '1) EXPOSED TO RAIN AND SUNLIGHT.',
 '1.0mm以下': '1.0 mm MAX.',
 '1.ばね定数(測定要領は下図1による)': '1. SPRING RATE (MEASURE AS SHOWN IN FIG. 1 BELOW)',
 '1.ばね特性は、右ばね特性線図の 内にあること。K=640kg/mm±15%': '1. SPRING CURVE WITHIN THE {GAP} ZONE OF CHART AT RIGHT. K=640 kg/mm ±15%',
 '1.バネ特性は、右バネ特性図の 内にあること。': '1. SPRING CURVE SHALL BE WITHIN THE {GAP} ZONE (CHART ON RIGHT).',
 '1.本品は2個で1セットとし、左図の様にセットした状態で使用する。': '1. TWO PIECES FORM ONE SET; USE AS ASSEMBLED IN THE FIGURE ON THE LEFT.',
 '1.本品はV1411-4215Aに対して、静的ばね定数、及びゴム形状が異なる。': '1. THIS PART DIFFERS FROM V1411-4215A IN STATIC SPRING RATE AND RUBBER SHAPE.',
 '1.本品は「標準品KA-50」に対して、ゴム材質が異なります。': '1. THIS PART DIFFERS FROM STANDARD PART KA-50 IN RUBBER MATERIAL.',
 '1.本品は標準品 REM-90 シリーズに対しばね定数、識別が異なる。': '1. THIS PART DIFFERS FROM THE STANDARD REM-90 SERIES IN SPRING RATE AND IDENTIFICATION.',
 '1.特性(2個1組で組付けたときの値。取付け状態参照。)': '1. CHARACTERISTICS (VALUES FOR A SET OF 2 PIECES ASSEMBLED; SEE INSTALLED CONDITION.)',
 '1.静的ばね定数': '1. STATIC SPRING RATE',
 '12.5S以下': '12.5S MAX.',
 '13.5 {\\C256;取付時 11.5}': '13.5 {\\C256;INSTALLED 11.5}',
 '1x10 回': '1x10 CYCLES',
 '2)軸直角方向荷重(Q方向)': '2) RADIAL LOAD (Q DIRECTION)',
 '2)雰囲気温度 -50%%dC~+80%%dC': '2) AMBIENT TEMPERATURE -50%%dC TO +80%%dC',
 '2.0mm以下': '2.0 mm MAX.',
 '2.A面(全面)は締結面(取付図参照)の為、ゴムバリなきこと。': '2. SURFACE A (ENTIRE SURFACE) IS A FASTENING SURFACE (SEE INSTALLATION DRAWING); NO RUBBER FLASH IS PERMITTED.',
 '2.ゴム材質 NR': '2. RUBBER MATERIAL: NR',
 '2.ゴム材質:耐熱NR': '2. RUBBER MATERIAL: HEAT-RESISTANT NR',
 '2.下記に示す耐久テスト後の、バネ特性は、右バネ特性図の 内にあること。': '2. AFTER DURABILITY TEST BELOW, SPRING CURVE SHALL BE WITHIN THE {GAP} ZONE.',
 '2.下記に示す耐久テスト後のばね特性は、右ばね特性図の 内にあること。': '2. AFTER DURABILITY TEST BELOW, SPRING CURVE SHALL BE WITHIN THE {GAP} ZONE.',
 '2.六角ナット、スプリングワッシャー各2個付きとします。': '2. SUPPLIED WITH 2 HEX NUTS AND 2 SPRING WASHERS.',
 '2.本品は継注品 RD461-42181 に対しマーキングが異なる。': '2. THIS PART DIFFERS FROM REPEAT-ORDER PART RD461-42181 IN MARKING.',
 '2.耐久性': '2. DURABILITY',
 '2.製品表面処理': '2. SURFACE TREATMENT',
 '3.A面(全面)及び内筒端面は締結面の為、ゴムバリなきこと。': '3. SURFACE A (ENTIRE SURFACE) AND INNER SLEEVE END FACES ARE FASTENING SURFACES; NO RUBBER FLASH IS PERMITTED.',
 '3.使用条件': '3. OPERATING CONDITIONS',
 '3.内筒(2)、外筒(3)は、化成処理をする。': '3. INNER SLEEVE (2) AND OUTER SLEEVE (3) SHALL BE CHEMICAL CONVERSION COATED.',
 '3.内筒(2)・外筒(3)は、化成処理をする。': '3. INNER SLEEVE (2) AND OUTER SLEEVE (3) SHALL BE CHEMICAL CONVERSION COATED.',
 '3.特性値': '3. CHARACTERISTIC VALUES',
 '3.耐久性能': '3. DURABILITY PERFORMANCE',
 '3.表面処理': '3. SURFACE TREATMENT:',
 '3.試作時品番:V1311-4215B': '3. PROTOTYPE PART NO.: V1311-4215B',
 '35S以下': '35S MAX.',
 '4.下記の使用条件で、耐久性に異常のないこと。': '4. NO DURABILITY PROBLEMS UNDER THE OPERATING CONDITIONS BELOW.',
 '4.下記の使用条件で、耐久性に異常の無いこと。': '4. NO DURABILITY PROBLEMS UNDER THE OPERATING CONDITIONS BELOW.',
 '4.内筒(2)は化成処理をする。': '4. INNER SLEEVE (2) SHALL BE CHEMICAL CONVERSION COATED.',
 '4.耐久性能については、下記の試験を実施後、有害な損傷なきこと。': '4. DURABILITY: NO HARMFUL DAMAGE AFTER THE FOLLOWING TEST.',
 '5.ゴム(1)と内筒(2)は加硫接着。': '5. RUBBER (1) AND INNER SLEEVE (2) ARE VULCANIZATION BONDED.',
 '5.本品は、154-01-21310に対し、ばね特性が異なる。': '5. THIS PART DIFFERS FROM 154-01-21310 IN SPRING CHARACTERISTICS.',
 '676~1352N間': 'BETWEEN 676 AND 1352 N',
 '676~2028N間': 'BETWEEN 676 AND 2028 N',
 '6x10 回': '6x10 CYCLES',
 '<> {\\C256;取付時 11.5}': '<> {\\C256;INSTALLED 11.5}',
 '<X方向ばね定数> : 104 N/mm (設計値)': '<X-DIR. SPRING RATE> : 104 N/mm (DESIGN VALUE)',
 '<Z方向ばね定数> : 610 N/mm (設計値)': '<Z-DIR. SPRING RATE> : 610 N/mm (DESIGN VALUE)',
 '<Z方向支持荷重> : ~1230 N': '<Z-DIR. SUPPORT LOAD> : UP TO 1230 N',
 '<Z方向許容荷重> : 2500 N': '<Z-DIR. ALLOWABLE LOAD> : 2500 N',
 '<製品質量> : 200 g': '<PRODUCT MASS> : 200 g',
 'A部': 'DETAIL A',
 'A面': 'SURFACE A',
 'B級': 'CLASS B',
 'B面': 'SURFACE B',
 'B面(全周)に、浮きゴムバリなきこと。': 'NO LOOSE RUBBER FLASH IS PERMITTED ON SURFACE B (ENTIRE CIRCUMFERENCE).',
 'C0.5以下': 'C0.5 MAX.',
 'C級': 'CLASS C',
 'NR系': 'NR BASE',
 'P方向': 'P DIRECTION',
 'P方向:1W±2.5Wにて100万回(40%%dC)': 'P DIRECTION: 1W ±2.5W, 1,000,000 CYCLES (40%%dC)',
 'P方向支持荷重最大値': 'MAX. SUPPORT LOAD IN P DIRECTION',
 'P方向測定範囲:440N~1320N 予備荷重:3520N テストスピード:10mm/min': 'P DIRECTION RANGE: 440 N TO 1320 N  PRELOAD: 3520 N  TEST SPEED: 10 mm/min',
 'P方向許容荷重': 'ALLOWABLE LOAD IN P DIRECTION',
 'P方向静的ばね定数': 'STATIC SPRING RATE IN P DIRECTION',
 'Q方向': 'Q DIRECTION',
 'Q方向: ±2.5Wにて100万回(40%%dC)': 'Q DIRECTION: ±2.5W, 1,000,000 CYCLES (40%%dC)',
 'Q方向測定範囲:440N~ 880N 予備荷重:2640N テストスピード:10mm/min': 'Q DIRECTION RANGE: 440 N TO 880 N  PRELOAD: 2640 N  TEST SPEED: 10 mm/min',
 'Q方向静的ばね定数(参考値)': 'STATIC SPRING RATE IN Q DIRECTION (REF.)',
 'R側': 'R SIDE',
 'STKM12A・SC': 'STKM12A / SC',
 'T.P.Hs=50(参考)': 'T.P.Hs=50 (REF.)',
 'T.P.Hs=52(参考)': 'T.P.Hs=52 (REF.)',
 'T.P.Hs=55(参考)': 'T.P.Hs=55 (REF.)',
 'T.P.Hs=A50(参考)': 'T.P.Hs=A50 (REF.)',
 'T.P.Hs=A52(参考)': 'T.P.Hs=A52 (REF.)',
 '\\A1;%%C39(R8の中心)': '\\A1;%%C39 (CENTER OF R8)',
 '\\A1;%%C42.3(R9の中心)': '\\A1;%%C42.3 (CENTER OF R9)',
 '\\A1;%%c66.9{\\H1.500000;\\S+0.5^ 0;}(取付穴径)': '\\A1;%%c66.9{\\H1.500000;\\S+0.5^ 0;} (MOUNTING HOLE DIA.)',
 '\\A1;%%c66.9{\\H1.5;\\S+0.5^ 0;}(取付穴径)': '\\A1;%%c66.9{\\H1.5;\\S+0.5^ 0;} (MOUNTING HOLE DIA.)',
 '\\A1;(%%C108以上)': '\\A1;(%%C108 MIN.)',
 '\\A1;(%%c108以上)': '\\A1;(%%c108 MIN.)',
 '\\A1;ストッパークリアランス': '\\A1;STOPPER CLEARANCE',
 '\\A1;繰り返し数 1.2x10{\\H0.7x;\\S5^ ;} 回': '\\A1;NUMBER OF CYCLES 1.2x10{\\H0.7x;\\S5^ ;}',
 'φ7程度、赤': 'APPROX. %%c7, RED',
 '※ 図面に指示なき寸法公差は、Sanki-STANDARD KSS11-3,4による。': '* DIMENSIONAL TOLERANCES NOT SPECIFIED ON THIS DRAWING SHALL CONFORM TO SANKI STANDARD KSS11-3 AND 4.',
 '※ 図面に指示なき寸法公差は、Sanki-STANDARD KSS11-3A,4Aによる。': '* DIMENSIONAL TOLERANCES NOT SPECIFIED ON THIS DRAWING SHALL CONFORM TO SANKI STANDARD KSS11-3A AND 4A.',
 '「01」': '"01"',
 '「CR」': '"CR"',
 '「RD461」浮出し': '"RD461" EMBOSSED',
 '「REM-90B」': '"REM-90B"',
 'えぐれなきこと': 'NO GOUGES',
 'を浮刻のこと': 'SHALL BE EMBOSSED.',
 'を超え': 'OVER',
 'ウェルディングボルト': 'WELDING BOLT',
 'エンジンマウント': 'ENGINE MOUNT',
 'クッション': 'CUSHION',
 'クッション内筒': 'CUSHION INNER SLEEVE',
 'クッション外筒': 'CUSHION OUTER SLEEVE',
 'ゴム': 'RUBBER',
 'ゴムテストピース硬さ:T.P.Hs=A80±3(ヤマニゴム自給材)': 'RUBBER TEST PIECE HARDNESS: T.P.Hs=A80 ±3 (YAMANI IN-HOUSE COMPOUND)',
 'ゴムバリ仕上げ高さ': 'RUBBER FLASH FINISH HEIGHT',
 'ゴム体積 Rub.Vol.': 'RUBBER VOLUME',
 'ゴム普通寸法公差': 'GENERAL RUBBER TOLERANCES',
 'ゴム硬さ変更': 'RUBBER HARDNESS CHANGED',
 'ゴム硬さ管理に変更。新図作成。': 'RUBBER HARDNESS CONTROL; NEW DRAWING.',
 'ゴム部には付着可とする。但し、内筒内面は除く。': 'ADHESION TO RUBBER IS ACCEPTABLE, EXCEPT ON THE INNER SURFACE OF THE INNER SLEEVE.',
 'ゴム部に塗装可とする。但し、内筒内面の膜厚は不問とする。': 'PAINT ON RUBBER ACCEPTABLE; FILM THICKNESS ON INNER SURFACE OF INNER SLEEVE NOT SPECIFIED.',
 'ストッパー': 'STOPPER',
 'ストッパークリアランス': 'STOPPER CLEARANCE',
 'タグ番号': 'TAG NO.',
 'テストスピード(mm/min)': 'TEST SPEED (mm/min)',
 'プレス抜き加工普通寸法公差': 'PRESS-BLANKING TOLERANCES',
 'プレート': 'PLATE',
 'メーカーマーク及び': 'EMBOSS THE MANUFACTURER MARK',
 'メーカーマーク及び製造刻印': 'MANUFACTURER MARK AND DATE STAMP',
 'ヤマニ自給材': 'YAMANI IN-HOUSE COMPOUND',
 'ランク': 'RANK',
 '三': 'THIRD',
 '三海': 'MIKAI',
 '上表参照': 'SEE TABLE',
 '上記条件にて耐久テスト後、異常なきこと。': 'NO ABNORMALITY AFTER DURABILITY TEST UNDER THE ABOVE CONDITIONS.',
 '中級': 'MEDIUM CLASS',
 '丸形防振ゴム': 'ROUND ANTI-VIBRATION RUBBER',
 '予備荷重(N)': 'PRELOAD (N)',
 '予備荷重:10000N テストスピード:3mm/min': 'PRELOAD: 10000 N  TEST SPEED: 3 mm/min',
 '仕上げ不要': 'NO FINISHING REQUIRED',
 '仕様': 'SPECIFICATIONS',
 '以上': 'OR MORE',
 '以下': 'OR LESS',
 '体積 Volume': 'VOLUME',
 '作 成': 'DRAWN',
 '作成年月日': 'DATE CREATED',
 '例)2012年5月:': 'EXAMPLE: MAY 2012:',
 '例)2014年8月:': 'EXAMPLE: AUGUST 2014:',
 '例)2021年10月:': 'EXAMPLE: OCTOBER 2021:',
 '保都': 'HOTO',
 '備 考': 'REMARKS',
 '元.10.23': "'19.10.23",
 '公差変更(%%C95 に)': 'TOLERANCE CHANGED (TO %%C95{GAP})',
 '内山': 'UCHIYAMA',
 '内筒': 'INNER SLEEVE',
 '冨羽': 'TOMIWA',
 '削り加工普通寸法公差': 'MACHINING TOLERANCES',
 '加藤': 'KATO',
 '半径方向荷重 P1 650~6500Kg': 'RADIAL LOAD P1 650~6500 kg',
 '半径方向荷重(P1)': 'RADIAL LOAD (P1)',
 '半径方向荷重P1 650~6500kg': 'RADIAL LOAD P1 650~6500 kg',
 '原管寸法 %%C96±0.1 x %%C86±0.1 x 36±0.1': 'RAW TUBE SIZE %%C96±0.1 x %%C86±0.1 x 36±0.1',
 '取付け状態(例)(機器の荷重によるたわみは考慮していません)': 'INSTALLED CONDITION (EXAMPLE) (DEFLECTION DUE TO EQUIPMENT LOAD IS NOT CONSIDERED)',
 '取付け状態(機器の荷重によるたわみは考慮していません)': 'INSTALLED CONDITION (DEFLECTION DUE TO EQUIPMENT LOAD IS NOT CONSIDERED)',
 '取付け状態にて測定。(ストッパーは、円盤型ストッパーで可。)': 'MEASURE IN THE INSTALLED CONDITION. (A DISC-TYPE STOPPER IS ACCEPTABLE.)',
 '名': 'NAME',
 '名 称': 'DESCRIPTION',
 '周期': 'FREQUENCY',
 '周波数': 'FREQUENCY',
 '周波数 1Hz': 'FREQUENCY 1 Hz',
 '和泉': 'IZUMI',
 '品': 'PART NO.',
 '品番「V1311-42151」': 'PART NO. "V1311-42151"',
 '品番変更(試作時品番:03071178-2)': 'PART NO. CHANGED (PROTOTYPE P/N: 03071178-2)',
 '品番変更(試作時品番:03071178-3)': 'PART NO. CHANGED (PROTOTYPE P/N: 03071178-3)',
 '品番変更及び図面調整': 'PART NO. CHANGED AND DRAWING ADJUSTED',
 '図面CAD化、材質訂正': 'DRAWING CONVERTED TO CAD; MATERIAL CORRECTED',
 '圧縮ばね定数Kc=5000N/mm±20%(参考)測定区間:100~4000N間': 'COMPRESSION SPRING RATE Kc=5000 N/mm ±20% (REF.)  MEASURING RANGE: 100 TO 4000 N',
 '堀井': 'HORII',
 '外周部のバリは\\P0.5mm以内のこと': 'FLASH ON OUTER PERIPHERY\\P0.5 mm MAX.',
 '外筒': 'OUTER SLEEVE',
 '多々納': 'TATANO',
 '寸法修正': 'DIMENSION CORRECTED',
 '寸法変更': 'DIMENSION CHANGED',
 '少量時 SS400': 'SMALL LOTS: SS400',
 '尺度': 'SCALE',
 '岡本': 'OKAMOTO',
 '平面部 %%C118以上': 'FLAT PART %%C118 MIN.',
 '平面部 %%C<>以上': 'FLAT PART %%C<> MIN.',
 '年': 'YEAR',
 '影山': 'KAGEYAMA',
 '承 認': 'APPROVED',
 '承認': 'APPD',
 '接着強度は2.9N/mm 以上': 'BOND STRENGTH: 2.9 N/mm  MIN.',
 '数': 'QTY',
 '文字の後にマーキング': 'MARKING AFTER THE CHARACTERS',
 '断面 A-A': 'SECTION A-A',
 '断面図': 'SECTION VIEW',
 '方向': 'DIR.',
 '日': 'DAY',
 '日付': 'DATE',
 '月': 'MONTH',
 '有松': 'ARIMATSU',
 '本品は、03071257-3とA部形状が異なる。': 'THIS PART DIFFERS FROM 03071257-3 IN THE SHAPE OF DETAIL A.',
 '材 質': 'MATERIAL',
 '材質 STKM11A E-C シームレス酸洗 (光輝焼鈍)': 'MATERIAL STKM11A E-C SEAMLESS, PICKLED (BRIGHT ANNEALED)',
 '来 歴・変 更 事 項': 'REVISION HISTORY / CHANGES',
 '株式会社KCM 殿': 'KCM CORPORATION',
 '株式会社小松製作所 御中': 'KOMATSU LTD.',
 '検 図': 'CHECKED',
 '標準品 REM-90B と同一品。': 'IDENTICAL TO STANDARD PART REM-90B.',
 '横部': 'YOKOBE',
 '法': 'PROJ.',
 '注入孔高さ': 'INJECTION HOLE HEIGHT',
 '注記': 'NOTES',
 '注記;化成処理をする為、有害なスケールのないこと。': 'NOTE: NO HARMFUL SCALE (FOR CHEMICAL CONVERSION COATING).',
 '注記変更(内径面取り指示削除)': 'NOTE CHANGED (BORE CHAMFER CALLOUT DELETED)',
 '注記追加': 'NOTE ADDED',
 '浮出し高さは0.2以内': 'EMBOSSING HEIGHT 0.2 MAX.',
 '測定範囲': 'MEASUREMENT RANGE',
 '測定要領': 'MEASUREMENT METHOD',
 '産業機器事業部': 'INDUSTRIAL MACHINERY DIVISION',
 '番': 'PART NO.',
 '番号': 'NO.',
 '称': 'NAME',
 '端部に有害なバリ、カエリ無き事': 'NO HARMFUL FLASH OR BURRS AT ENDS',
 '端面はかえりなきこと': 'NO BURRS ON END FACES',
 '端面はかえりなきこと。': 'NO BURRS ON END FACES.',
 '符号': 'CODE',
 '糸面取りのこと': 'BREAK EDGES',
 '糸面取りのこと(両端)': 'BREAK EDGES (BOTH ENDS)',
 '納入仕様書': 'DELIVERY SPECIFICATION',
 '組付け要領(尺度:Free)': 'ASSEMBLY METHOD (SCALE: FREE)',
 '繰り返し数': 'NUMBER OF CYCLES',
 '繰り返し数 1.2x10 回': 'NUMBER OF CYCLES 1.2x10',
 '耐久回数': 'NUMBER OF CYCLES',
 '耐熱CR': 'HEAT-RES. CR',
 '耐熱NR': 'HEAT-RES. NR',
 '膜厚15µm以上/ゴム部に付着可とする。内筒内面は除く': 'FILM THICKNESS: 15 µm MIN. / ADHESION TO RUBBER IS ACCEPTABLE, EXCEPT INNER SURFACE OF INNER SLEEVE.',
 '草下': 'KUSASHITA',
 '荷重条件': 'LOAD CONDITIONS',
 '蓮井': 'HASUI',
 '藤原': 'FUJIWARA',
 '藤田': 'FUJITA',
 '製品表面硬さ:Hs=A85±5(参考)': 'PRODUCT SURFACE HARDNESS: Hs=A85 ±5 (REF.)',
 '製造図面': 'MANUFACTURING DRAWING',
 '製造年月を浮刻のこと': 'AND DATE OF MANUFACTURE.',
 '角': 'ANGLE',
 '訂正': 'REV.',
 '試験後有害な損傷なきこと。': 'NO HARMFUL DAMAGE AFTER THE TEST.',
 '誤記訂正': 'ERRATA CORRECTED',
 '識別表示': 'IDENTIFICATION',
 '識別表示(浮刻)': 'IDENTIFICATION (EMBOSSED)',
 '質量 Mass': 'MASS',
 '質量・体積、品質ランク等追記': 'MASS, VOLUME, QUALITY RANK ETC. ADDED',
 '質量・体積追記': 'MASS AND VOLUME ADDED',
 '軸方向ばね定数(P方向) K =18630N/mm±20%': 'AXIAL SPRING RATE (P DIRECTION) K = 18630 N/mm ±20%',
 '軸方向荷重 P2 0~5100Kg': 'AXIAL LOAD P2 0~5100 kg',
 '軸方向荷重(P2)': 'AXIAL LOAD (P2)',
 '軸方向荷重P1 0~5100kg': 'AXIAL LOAD P1 0~5100 kg',
 '軸直角方向ばね定数(Q方向) K =25500N/mm(参考値)': 'RADIAL SPRING RATE (Q DIRECTION) K = 25500 N/mm (REF.)',
 '金具': 'METAL PARTS',
 '金具下処理:No.21': 'METAL PRETREATMENT: No. 21',
 '金具下処理:化成処理(リン酸亜鉛皮膜)': 'METAL PRETREATMENT: CHEMICAL CONVERSION COATING (ZINC PHOSPHATE)',
 '金具図面': 'METAL PART DRAWING',
 '金具部処理:黒色塗装(アクリル系水性エマルション塗料/アスカKK)膜厚15µm以上': 'METAL PART TREATMENT: BLACK COATING (ACRYLIC WATER-BASED EMULSION PAINT / ASUKA KK), FILM THICKNESS 15 µm MIN.',
 '金具部表面処理:黒色塗装(アクリル系水性エマルション塗料/アスカKK)': 'METAL PART SURFACE TREATMENT: BLACK COATING (ACRYLIC WATER-BASED EMULSION PAINT / ASUKA KK)',
 '金田': 'KANEDA',
 '雨水、日射あり': 'EXPOSED TO RAIN AND SUNLIGHT',
 '雰囲気温度': 'AMBIENT TEMPERATURE',
 '電気亜鉛めっき': 'ZINC ELECTROPLATING',
 '電気亜鉛めっき(有色クロメート)': 'ZINC ELECTROPLATING (YELLOW CHROMATE)',
 '高さ:0.5mm以下': 'HEIGHT: 0.5 mm MAX.',
 '高さ:1.0mm以下': 'HEIGHT: 1.0 mm MAX.',
 '高さ:2.0mm以下': 'HEIGHT: 2.0 mm MAX.',
 '高月': 'TAKATSUKI',
}
UNCERTAIN_NAMES = {'保都', '草下', '多々納'}
